---
id: labguide
name: AEC Lab Guide

content:
  url: https://raw.githubusercontent.com/leroyjvargis/labguides-workshopper/master

vars:
  USER_NAME: "(email)"
  USER_PASSWORD: "(email)"
  GIT_HOST: github
  DOCS_URL: docs.openshift.org

modules:
  activate:
  - part1
  - part2